export const SOCKET_PERSONAL_CONNECTION_START =
	'SOCKET_PERSONAL_CONNECTION_START' as const;
export const SOCKET_PERSONAL_CONNECTION_CLOSE =
	'SOCKET_PERSONAL_CONNECTION_CLOSE' as const;
export const SOCKET_PERSONAL_CONNECTION_SUCCESS =
	'SOCKET_PERSONAL_CONNECTION_SUCCESS' as const;
export const SOCKET_PERSONAL_CONNECTION_ERROR =
	'SOCKET_PERSONAL_CONNECTION_ERROR' as const;
export const SOCKET_PERSONAL_GET_MESSAGE =
	'SOCKET_PERSONAL_GET_MESSAGE' as const;
export const SOCKET_PERSONAL_SEND_MESSAGE =
	'SOCKET_PERSONAL_SEND_MESSAGE' as const;
export const SOCKET_PERSONAL_CONNECTION_CLOSED =
	'SOCKET_PERSONAL_CONNECTION_CLOSED' as const;
