export const SOCKET_CONNECTION_START = 'SOCKET_CONNECTION_START' as const;
export const SOCKET_CONNECTION_CLOSE = 'SOCKET_CONNECTION_CLOSE' as const;
export const SOCKET_CONNECTION_SUCCESS = 'SOCKET_CONNECTION_SUCCESS' as const;
export const SOCKET_CONNECTION_ERROR = 'SOCKET_CONNECTION_ERROR' as const;
export const SOCKET_GET_MESSAGE = 'SOCKET_GET_MESSAGE' as const;
export const SOCKET_SEND_MESSAGE = 'SOCKET_SEND_MESSAGE' as const;
export const SOCKET_CONNECTION_CLOSED = 'SOCKET_CONNECTION_CLOSED' as const;
